version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672"  # webu
  mongodb:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
  smtp:
    image: reachfive/fake-smtp-server
    ports:
      - "1080:1080"
      - "1025:1025"

  public-service:
    image: public-service
    ports:
      - "8888:8888"
    depends_on:
      - rabbitmq

  subscription-service:
    image: subscription-service
    depends_on:
      - rabbitmq
      - mongodb

  email:
    image: email-service
    depends_on:
      - rabbitmq
